/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/ui/select/select-actionsheet`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/select/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tests/index` | `/tests/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/report/index` | `/report/index`; params?: Router.UnknownInputParams; } | { pathname: `/admin/index`; params?: Router.UnknownInputParams; } | { pathname: `/admin/patients`; params?: Router.UnknownInputParams; } | { pathname: `/admin/guides`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(history)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/tests/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/ui/select/select-actionsheet`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/select/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tests/index` | `/tests/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/report/index` | `/report/index`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/index`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/patients`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/guides`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(history)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/tests/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/ui/select/select-actionsheet${`?${string}` | `#${string}` | ''}` | `/../components/ui/select/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tests/index${`?${string}` | `#${string}` | ''}` | `/tests/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/report/index${`?${string}` | `#${string}` | ''}` | `/report/index${`?${string}` | `#${string}` | ''}` | `/admin/index${`?${string}` | `#${string}` | ''}` | `/admin/patients${`?${string}` | `#${string}` | ''}` | `/admin/guides${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(history)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/ui/select/select-actionsheet`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/select/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tests/index` | `/tests/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/report/index` | `/report/index`; params?: Router.UnknownInputParams; } | { pathname: `/admin/index`; params?: Router.UnknownInputParams; } | { pathname: `/admin/patients`; params?: Router.UnknownInputParams; } | { pathname: `/admin/guides`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(history)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | `/tests/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/tests/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
